title: AndroidDeals
description: 一些简短实用的教程
author: AndroidDeals
logo: /hcz-jekyll-blog/static/img/avatar.png
github: https://androiddeals.github.io/


baseurl: "https://androiddeals.github.io"
url: "https://androiddeals.github.io"

allowsearch: true



share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: false
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
